<?php

namespace AppBundle\Repository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllUsersWithBirthDateByDate($date): ?array
    {
        $query = $this->createQueryBuilder('u')
            ->where('u.birthDate is not null')
            ->andWhere('u.createdAt >= :date')
            ->setParameter('date', new \DateTime($date), \Doctrine\DBAL\Types\Type::DATETIME)
            ->getQuery();

        return $query->getResult();
    }
}
