<?php

namespace AppBundle\Repository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllUsersWithBirthDate(): ?array
    {
        $query = $this->createQueryBuilder('u')
            ->where('u.birthdate is not null')
            ->getQuery();

        return $query->getResult();
    }
}
