# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [in_memory, db_provider]
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$o7af6RGpbnsTvnnhKuGxter7CVArvHNHzi6QNKYyaNhLYBcLkrPE.
                        roles: ['ROLE_ADMIN', 'ROLE_USER']

        db_provider:
            entity:
                class: AppBundle\Entity\User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false



        main:
            form_login:
                login_path: user_login
                check_path: user_login
                provider: chain_provider
            anonymous: ~
            json_login:
                check_path: api_login
            logout:
                path:   /logout
                target: /login
            pattern:    ^/
            provider: chain_provider
            http_basic:
                provider: chain_provider



    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api/users, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/age, roles: ROLE_ADMIN }

              # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
